### ISSUE TITLE
Incompatibility with dnspython 2.7.0

### ISSUE THREAD

**Issue by frenzymadness** [dnsviz/dnsviz#151]
It seems that with version 2.7.0, dnspython started to provide COOKIE and Report-Channel EDNS0 options and that breaks tests of dnsviz. For example:

```
_____ DNSProbeRunOfflineTestCase.test_dnsviz_probe_auth_local_signed_nsec ______

self = <test_71_dnsviz_probe_run_offline.DNSProbeRunOfflineTestCase testMethod=test_dnsviz_probe_auth_local_signed_nsec>

    def test_dnsviz_probe_auth_local_signed_nsec(self):
>       self._probe_zone('signed-nsec', True)

tests/test_71_dnsviz_probe_run_offline.py:53: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/test_71_dnsviz_probe_run_offline.py:50: in _probe_zone
    self.assertReturnCode(subprocess.call(cmd, stdout=fh))
tests/test_71_dnsviz_probe_run_offline.py:33: in assertReturnCode
    self.assertEqual(retcode, 0)
E   AssertionError: 4 != 0
----------------------------- Captured stderr call -----------------------------
Error analyzing example.com
Traceback (most recent call last):
  File "/builddir/build/BUILD/dnsviz-0.11.0-build/BUILDROOT/usr/lib/python3.13/site-packages/dnsviz/commands/probe.py", line 167, in _analyze
    a = cls(name, rdclass=rdclass, dlv_domain=dlv_domain, try_ipv4=try_ipv4, try_ipv6=try_ipv6, client_ipv4=client_ipv4, client_ipv6=client_ipv6, query_class_mixin=query_class_mixin, ceiling=c, edns_diagnostics=edns_diagnostics, explicit_delegations=explicit_delegations, stop_at_explicit=stop_at_explicit, odd_ports=odd_ports, extra_rdtypes=extra_rdtypes, explicit_only=explicit_only, analysis_cache=cache, cache_level=cache_level, analysis_cache_lock=cache_lock, transport_manager=tm, th_factories=th_factories, resolver=resolver)
  File "/builddir/build/BUILD/dnsviz-0.11.0-build/BUILDROOT/usr/lib/python3.13/site-packages/dnsviz/analysis/online.py", line 1146, in __init__
    self.local_ceiling = self._detect_ceiling(ceiling)[0]
                         ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/builddir/build/BUILD/dnsviz-0.11.0-build/BUILDROOT/usr/lib/python3.13/site-packages/dnsviz/analysis/online.py", line 1233, in _detect_ceiling
    ans = self.resolver.query_for_answer(ceiling, dns.rdatatype.NS, self.rdclass)
  File "/builddir/build/BUILD/dnsviz-0.11.0-build/BUILDROOT/usr/lib/python3.13/site-packages/dnsviz/resolver.py", line 438, in query_for_answer
    response, server = self.query(qname, rdtype, rdclass)
                       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/dnsviz-0.11.0-build/BUILDROOT/usr/lib/python3.13/site-packages/dnsviz/resolver.py", line 426, in query
    l = self._query(qname, rdtype, rdclass, 0, self.SRC_NONAUTH_ANS)
  File "/builddir/build/BUILD/dnsviz-0.11.0-build/BUILDROOT/usr/lib/python3.13/site-packages/dnsviz/resolver.py", line 595, in _query
    server_cookie = response.get_server_cookie()
  File "/builddir/build/BUILD/dnsviz-0.11.0-build/BUILDROOT/usr/lib/python3.13/site-packages/dnsviz/response.py", line 325, in get_server_cookie
    if cookie_opt is not None and len(cookie_opt.data) > 8:
                                      ^^^^^^^^^^^^^^^
AttributeError: 'CookieOption' object has no attribute 'data'
```

There is a completely new CookieOption class in dnspython since 2.7.0 release candidate 1: https://github.com/rthalley/dnspython/commit/32c66483794c3d483d9836fd95a8af1a7d01c3d2

**Comment by cdeccio** [comment]
Oh, that's fun.  That also happened with #134.  I wish that there were a little better backwards compatibility there, particularly for a minor version.  I'll take a look soon...

**Comment by frenzymadness** [comment]
Is there anything I can help you with here?

**Comment by cdeccio** [comment]
Sorry, will take another look at this soon.  The short answer is that the new functionality introduced in dnspython >= 2.6 has made things complicated, and there is no easy solution.

**Comment by frenzymadness** [comment]
Let me know if I can help to move this forward.

**Comment by cdeccio** [comment]
See also 71d00a4 and #161.

**Comment by frenzymadness** [comment]
Thank you!
