### ISSUE TITLE
-A broken in docker for mac

### ISSUE THREAD

**Issue by SvenVD** [dnsviz/dnsviz#32]
[root@23beedbfd2bf dnsviz]# /usr/bin/dnsviz probe -A  -d 3 -4 dnssec-failed.org
Error analyzing dnssec-failed.org
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dnsviz/commands/probe.py", line 146, in _analyze
    a = cls(name, dlv_domain=dlv_domain, try_ipv4=try_ipv4, try_ipv6=try_ipv6, client_ipv4=client_ipv4, client_ipv6=client_ipv6, query_class_mixin=query_class_mixin, ceiling=c, edns_diagnostics=edns_diagnostics, explicit_delegations=explicit_delegations, stop_at_explicit=stop_at_explicit, odd_ports=odd_ports, extra_rdtypes=extra_rdtypes, explicit_only=explicit_only, analysis_cache=cache, cache_level=cache_level, analysis_cache_lock=cache_lock, transport_manager=tm, th_factories=th_factories, resolver=resolver)
  File "/usr/lib/python2.7/site-packages/dnsviz/analysis/online.py", line 1072, in __init__
    self.local_ceiling = self._detect_ceiling(ceiling)[0]
  File "/usr/lib/python2.7/site-packages/dnsviz/analysis/online.py", line 1163, in _detect_ceiling
    ans = self.resolver.query_for_answer(ceiling, dns.rdatatype.NS, dns.rdataclass.IN)
  File "/usr/lib/python2.7/site-packages/dnsviz/resolver.py", line 423, in query_for_answer
    response, server = self.query(qname, rdtype, rdclass)
  File "/usr/lib/python2.7/site-packages/dnsviz/resolver.py", line 411, in query
    l = self._query(qname, rdtype, rdclass, 0, self.SRC_NONAUTH_ANS)
  File "/usr/lib/python2.7/site-packages/dnsviz/resolver.py", line 551, in _query
    a_rrset = self._query(ns_name, a_rdtype, dns.rdataclass.IN, level + 1, self.SRC_ADDITIONAL, starting_domain=sd)[-2]
  File "/usr/lib/python2.7/site-packages/dnsviz/resolver.py", line 564, in _query
    q.execute(tm=self._transport_manager, th_factories=self._th_factories)
  File "/usr/lib/python2.7/site-packages/dnsviz/query.py", line 1468, in _func
    return func(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/dnsviz/query.py", line 1478, in execute
    self.execute_queries(self, ignore_queryid=ignore_queryid, tm=tm, th_factories=th_factories)
  File "/usr/lib/python2.7/site-packages/dnsviz/query.py", line 1427, in execute_queries
    raise SourceAddressBindError('Unable to bind to local address (%s)' % (errno.errorcode[errno1]))
SourceAddressBindError: Unable to bind to local address (EADDRNOTAVAIL)

I tested the same docker container on docker on centos 7 host and there I did not have this issue. The container itself is the official docker centos 7 from dockerhub. I tested to run bind and httpd in the same container and they had no problems binding to a port. Please advise.

(I have no issue on docker for mac when I do not use the -A option)

Docker for mac version:
Version 17.12.0-ce-mac49 (21995)

Thanks

**Comment by cdeccio** [comment]
See also #45 .

Take a look at the the notes on the README.md under "Docker" to see if that helps. In particular, see the section on setting up a host network.

**Comment by cdeccio** [comment]
DNSViz usage within a Docker container is documented in README.md (9964eb933 by @tomaskrizek - thanks!).  That fixes #45 and I believe it will fix this one too.
