### ISSUE TITLE
Parsing of resolv.conf should be more robust

### ISSUE THREAD

**Issue by bortzmeyer** [dnsviz/dnsviz#4]
```
% dnsget  bortzmeyer.org > ../bortzmeyer.org.json    
Traceback (most recent call last):
  File "./bin/dnsget", line 37, in <module>
    from dnsviz.analysis import Analyst, DomainNameAnalysis, get_client_addresses, NetworkConnectivityException, _resolver
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/analysis.py", line 137, in <module>
    _resolver = Resolver.Resolver.from_file('/etc/resolv.conf', StandardRecursiveQueryCD)
  File "/usr/local/lib/python2.7/dist-packages/dnsviz/resolver.py", line 99, in from_file
    if words[0] == 'nameserver':
IndexError: list index out of range
```

Just because there was an empty line in resolv.conf. When deleting it, it worked fine.

**Comment by cdeccio** [comment]
fixed in 86e7b1
