### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by pstast** [dnsviz/dnsviz#74]
I often get the following error. It is completely random. When I run the same test again, no error is reported.

```
/usr/local/bin/dnsviz probe -p -A -R 'NS' -o '/data/web/tmp/tmpGfXmVqzWt9SmF5em.json' 'rhybar.cz' 2>&1
```
```
Analyzing cz (stub)
Analyzing rhybar.cz
Error analyzing rhybar.cz
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/dnsviz/commands/probe.py", line 166, in _analyze
    return a.analyze()
  File "/usr/local/lib/python3.7/dist-packages/dnsviz/analysis/online.py", line 1513, in analyze
    return self._analyze(self.name)
  File "/usr/local/lib/python3.7/dist-packages/dnsviz/analysis/online.py", line 1652, in _analyze
    self._analyze_name(name_obj)
  File "/usr/local/lib/python3.7/dist-packages/dnsviz/analysis/online.py", line 1686, in _analyze_name
    yxdomain = self._analyze_delegation(name_obj)
  File "/usr/local/lib/python3.7/dist-packages/dnsviz/analysis/online.py", line 1895, in _analyze_delegation
    query.execute(tm=self.transport_manager, th_factories=self.th_factories)
  File "/usr/local/lib/python3.7/dist-packages/dnsviz/query.py", line 1589, in _func
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/dnsviz/query.py", line 1599, in execute
    self.execute_queries(self, ignore_queryid=ignore_queryid, tm=tm, th_factories=th_factories)
  File "/usr/local/lib/python3.7/dist-packages/dnsviz/query.py", line 1497, in execute_queries
    response = qh.handle_response(qtm.res, response, response_time, qtm.src, qtm.sport)
  File "/usr/local/lib/python3.7/dist-packages/dnsviz/query.py", line 811, in handle_response
    retry_action = handler.handle(response_wire, response, response_time)
  File "/usr/local/lib/python3.7/dist-packages/dnsviz/query.py", line 378, in handle
    self._request.payload = self._reduced_payload
AttributeError: can't set attribute
```

**Comment by cdeccio** [comment]
When an analysis query times out, it tries again with reduced EDNS payload size.  Thus, timeout is what makes it reach the point in the code that is erroring out.  First, could you try to reproduce the error by making the first query time out?  You could (for example) use a firewall rule that blocks outgoing packets to one of the auth servers you are analyzing, so it is forced to try again.

**Comment by pstast** [comment]
This error is really caused by DNS query timeout, I blocked one of the servers on firewall.

But why does it end with magical error `AttributeError: can't set attribute`? It is confusing and looks like some bug in the code. Should dnsviz retry the query? Or write some better error message about DNS query timeout?

**Comment by pstast** [comment]
Why does it actually fail completely when one of the DNS servers does not respond? Is this intentional behavior?

**Comment by cdeccio** [comment]
No, this is not intentional behavior.  It is actually supposed to set the attribute 😄 .  What version of dnspython are you using?  I wonder if they have made it a read-only attribute or something?

**Comment by pstast** [comment]
```
# pip3 show dnspython
Name: dnspython
Version: 2.1.0
Summary: DNS toolkit
Home-page: http://www.dnspython.org
Author: Bob Halley
Author-email: halley@dnspython.org
License: ISC
Location: /usr/local/lib/python3.7/dist-packages
Requires: 
Required-by: 
```

Python 3.7 is from Debian Buster repo

**Comment by cdeccio** [comment]
Okay, I'll have to see if I can reproduce it here and why it has that behavior.  Definitely not intended.

**Comment by cdeccio** [comment]
Looks like it is maybe this update between 2.0 and 2.1:

https://github.com/rthalley/dnspython/commit/1c1db38fe2d4877d2d3ea86130310dc634223355
