### ISSUE TITLE
Can't graph broken DNSSEC test sites

### ISSUE THREAD

**Issue by ioc32** [dnsviz/dnsviz#8]
I've tried to probe (recursive querying) and graph the following labels using 0.4.0 release:
  - www.dnssec-failed.org
  - www.rhybar.cz
  - bad-sig.dane.verisignlabs.com

bad-sig.dane.verisignlabs.com is OK but www.dnssec-failed.org and www.rhybar.cz aren't.
Here's the output for www.dnssec-failed.org [1], www.rhybar.cz yields similar output.

The local resolver is working OK [2], as well as dnsviz grok [3]. 

If nobody else can reproduce, I can upload the probe and grok results.

Bug or pebkac? :-)

[1]
test# dnsviz probe -s 127.0.0.1 www.dnssec-failed.org | dnsviz graph -R a -Thtml -O
Analyzing www.dnssec-failed.org
Analyzing dnssec-failed.org
Analyzing org
Analyzing .
Traceback (most recent call last):
  File "/usr/bin/dnsviz", line 68, in <module>
    main()
  File "/usr/bin/dnsviz", line 65, in main
    mod.main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/dnsviz/commands/graph.py", line 288, in main
    finish_graph(G, [name_obj], rdtypes, trusted_keys, fmt, '%s.%s' % (name, fmt))
  File "/usr/lib/python2.7/site-packages/dnsviz/commands/graph.py", line 79, in finish_graph
    js_img = G.draw('js')
  File "/usr/lib/python2.7/site-packages/dnsviz/viz/dnssec.py", line 263, in draw
    img = self.to_raphael()
  File "/usr/lib/python2.7/site-packages/dnsviz/viz/dnssec.py", line 250, in to_raphael
    svg = self.G.draw(format='svg', prog='dot')
  File "/usr/lib64/python2.7/site-packages/pygraphviz/agraph.py", line 1474, in draw
    data = self._run_prog(prog, args)
  File "/usr/lib64/python2.7/site-packages/pygraphviz/agraph.py", line 1335, in _run_prog
    raise IOError(b"".join(errors))
IOError: dot: mincross.c:1314: flat_reorder: Assertion `constraining_flat_edge(g,v,e) == 0' failed.

[2]
test# dig @127.0.0.1 www.dnssec-failed.org a +dnssec

; <<>> DiG 9.9.4-RedHat-9.9.4-18.el7_1.5 <<>> @127.0.0.1 www.dnssec-failed.org a +dnssec
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 63152
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;www.dnssec-failed.org.         IN      A

;; Query time: 84 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Oct 13 20:45:56 CEST 2015
;; MSG SIZE  rcvd: 50

[3]
test# dnsviz probe -s 127.0.0.1 www.dnssec-failed.org | dnsviz grok -o /tmp/www.dnssec-failed.org.grokked.json
Analyzing www.dnssec-failed.org
Analyzing dnssec-failed.org
Analyzing org
Analyzing .
test# ls -ahl !$
ls -ahl /tmp/www.dnssec-failed.org.grokked.json
-rw-r--r-- 1 root root 16K Oct 13 20:48 /tmp/www.dnssec-failed.org.grokked.json
test# jq . !$ &>/dev/null && echo $?
jq . /tmp/www.dnssec-failed.org.grokked.json &>/dev/null && echo $?
0

**Comment by cdeccio** [comment]
@ioc32 thanks for the report.  Could you tell me what version of graphviz you are using?

**Comment by ioc32** [comment]
test# rpm -qa graphviz*
graphviz-2.30.1-19.el7.x86_64
graphviz-gd-2.30.1-19.el7.x86_64
graphviz-python-2.30.1-19.el7.x86_64
graphviz-devel-2.30.1-19.el7.x86_64

test# pip show pygraphviz | egrep ^Version
Version: 1.3.1

On Centos7, packages installed from the base repo.
Should I try a newer version?

**Comment by cdeccio** [comment]
I've used 2.38.0 for most development and testing.  Could you try with that version to see if it fixes the issue?  In the mean time, I'll try to track down the code that seems to be giving graphviz grief to see if there's a workaround, so things will work on Centos7.

**Comment by ioc32** [comment]
ACK.

Graphviz seem to provide a YUM repo themselves [1], I'll give it a try and let you know!

[1] http://www.graphviz.org/Download_linux_rhel.php

**Comment by ioc32** [comment]
Running 'dnsviz probe www.dnssec-failed.org | dnsviz graph -R a -Thtml -O' works OK, but running a similar command with -s or -A explode. Trying to generate png files instead, it does not explode but it does not work either [1].

Would you like to close the issue by making graphviz 2.30+ a requirement, or would you rather patch the code instead?

[1]
[root@localhost dnsviz]# dnsviz probe -A www.dnssec-failed.org | dnsviz graph -R a -Thtml -O
No global IPv6 connectivity detected
Analyzing org (stub)
Analyzing dnssec-failed.org
Analyzing www.dnssec-failed.org
Traceback (most recent call last):
  File "/bin/dnsviz", line 80, in <module>
    main()
  File "/bin/dnsviz", line 77, in main
    mod.main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/dnsviz/commands/graph.py", line 306, in main
    finish_graph(G, [name_obj], rdtypes, trusted_keys, fmt, '%s.%s' % (name, fmt))
  File "/usr/lib/python2.7/site-packages/dnsviz/commands/graph.py", line 79, in finish_graph
    js_img = G.draw('js')
  File "/usr/lib/python2.7/site-packages/dnsviz/viz/dnssec.py", line 271, in draw
    img = self.to_raphael()
  File "/usr/lib/python2.7/site-packages/dnsviz/viz/dnssec.py", line 258, in to_raphael
    svg = self.G.draw(format='svg', prog='dot')
  File "/usr/lib64/python2.7/site-packages/pygraphviz/agraph.py", line 1474, in draw
    data = self._run_prog(prog, args)
  File "/usr/lib64/python2.7/site-packages/pygraphviz/agraph.py", line 1335, in _run_prog
    raise IOError(b"".join(errors))
IOError: dot: mincross.c:1314: flat_reorder: Assertion `constraining_flat_edge(g,v,e) == 0' failed.

[root@localhost dnsviz]# dnsviz probe -s 127.0.0.1 www.dnssec-failed.org | dnsviz graph -R a -Thtml -O
Analyzing www.dnssec-failed.org
Analyzing dnssec-failed.org
Analyzing org
Analyzing .
Traceback (most recent call last):
  File "/bin/dnsviz", line 80, in <module>
    main()
  File "/bin/dnsviz", line 77, in main
    mod.main(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/dnsviz/commands/graph.py", line 306, in main
    finish_graph(G, [name_obj], rdtypes, trusted_keys, fmt, '%s.%s' % (name, fmt))
  File "/usr/lib/python2.7/site-packages/dnsviz/commands/graph.py", line 79, in finish_graph
    js_img = G.draw('js')
  File "/usr/lib/python2.7/site-packages/dnsviz/viz/dnssec.py", line 271, in draw
    img = self.to_raphael()
  File "/usr/lib/python2.7/site-packages/dnsviz/viz/dnssec.py", line 258, in to_raphael
    svg = self.G.draw(format='svg', prog='dot')
  File "/usr/lib64/python2.7/site-packages/pygraphviz/agraph.py", line 1474, in draw
    data = self._run_prog(prog, args)
  File "/usr/lib64/python2.7/site-packages/pygraphviz/agraph.py", line 1335, in _run_prog
    raise IOError(b"".join(errors))
IOError: dot: mincross.c:1314: flat_reorder: Assertion `constraining_flat_edge(g,v,e) == 0' failed.

[root@localhost dnsviz]# dnsviz probe -s 127.0.0.1 www.dnssec-failed.org | dnsviz graph -R a -Tpng -O
Analyzing www.dnssec-failed.org
Analyzing dnssec-failed.org
Analyzing org
Analyzing .
None: "www.dnssec-failed.org.png"

[root@localhost dnsviz]# dnsviz probe -A www.dnssec-failed.org | dnsviz graph -R a -Tpng -O
No global IPv6 connectivity detected
Analyzing org (stub)
Analyzing dnssec-failed.org
Analyzing www.dnssec-failed.org
None: "www.dnssec-failed.org.png"

**Comment by cdeccio** [comment]
Please try tweaking the code with this:

```
sed -i '' -e "s/, minlen='0'//" dnsviz/viz/dnssec.py
```

Then re-install.  Please let me know if that works.  It seems to work on my end with no adverse effects to the image.

**Comment by cdeccio** [comment]
Sorry, that was for the sed distributed with Mac.  For GNU sed, try:
```
sed -i "s/, minlen='0'//" dnsviz/viz/dnssec.py
```
