### ISSUE TITLE
dnsviz graph: IndexError: list index out of range

### ISSUE THREAD

**Issue by rithvikvibhu** [dnsviz/dnsviz#99]
I realize that the public resolver used here isn't returning records properly right now (recursion not available, lol) but still wanted to leave this here because it causes the graph command to throw an error and quit. Maybe can be handled gracefully?

Just the probe json:

```sh
❯ dnsviz probe -s 103.196.38.38 nameboard
```
```json
{".": {"type": "recursive", "stub": false, "cookie_standin": "cccccccccccccccc", "cookie_bad": "bbbbbbbbbbbbbbbb", "analysis_start": "2022-03-22 17:05:18 UTC", "analysis_end": "2022-03-22 17:05:18 UTC", "clients_ipv4": ["104.131.48.122"], "clients_ipv6": [], "cookie_rdtype": "NS", "explicit_delegation": true, "queries": [{"qname": ".", "qclass": "IN", "qtype": "NS", "options": {"flags": 256, "edns_version": 0, "edns_max_udp_payload": 4096, "edns_flags": 32768, "edns_options": [[10, "51c1bb438e772638"]], "tcp": false}, "responses": {"103.196.38.38": {"104.131.48.122": {"message": "7SuBBQABAAAAAAABAAACAAEAACkGkAAAgAAAAA==", "msg_size": 28, "time_elapsed": 42, "history": []}}}}]}, "nameboard.": {"type": "recursive", "stub": false, "cookie_standin": "cccccccccccccccc", "cookie_bad": "bbbbbbbbbbbbbbbb", "analysis_start": "2022-03-22 17:05:18 UTC", "analysis_end": "2022-03-22 17:05:18 UTC", "clients_ipv4": ["104.131.48.122"], "clients_ipv6": [], "parent": ".", "cookie_rdtype": "NS", "explicit_delegation": true, "queries": [{"qname": "nameboard.", "qclass": "IN", "qtype": "NS", "options": {"flags": 256, "edns_version": 0, "edns_max_udp_payload": 4096, "edns_flags": 32768, "edns_options": [[10, "51c1bb438e772638"]], "tcp": false}, "responses": {"103.196.38.38": {"104.131.48.122": {"message": "IgqFAAABAAAAAQABCW5hbWVib2FyZAAAAgABwAwABgABAAAIRABCAWENbWlzY29uZmlndXJlZAhwb3dlcmRucwZzZXJ2ZXIACmhvc3RtYXN0ZXLADHh3uSYAACowAAAOEAAJOoAAAA4QAAApBpAAAIAAAAA=", "msg_size": 116, "time_elapsed": 39, "history": []}}}}]}, "_meta._dnsviz.": {"version": 1.2, "names": ["nameboard."]}}
```

and passing it to graph:

```sh
❯ dnsviz probe -s 103.196.38.38 nameboard | dnsviz graph -Thtml -t tk.txt
```
```
Analyzing nameboard
Analyzing .
Traceback (most recent call last):
  File "/home/rithvik/.local/bin/dnsviz", line 136, in <module>
    main()
  File "/home/rithvik/.local/bin/dnsviz", line 133, in main
    mod.main(args)
  File "/home/rithvik/.local/lib/python3.8/site-packages/dnsviz/commands/graph.py", line 483, in main
    G.graph_rrset_auth(name_obj, qname, rdtype)
  File "/home/rithvik/.local/lib/python3.8/site-packages/dnsviz/viz/dnssec.py", line 1232, in graph_rrset_auth
    nodata_node = self.add_rrset_non_existent(name_obj, my_zone_obj, neg_response_info, False, False)
  File "/home/rithvik/.local/lib/python3.8/site-packages/dnsviz/viz/dnssec.py", line 821, in add_rrset_non_existent
    rrset_serialized = rrset_info.serialize(consolidate_clients=consolidate_clients, html_format=True, map_ip_to_ns_name=name_obj.zone.get_ns_name_for_ip)
  File "/home/rithvik/.local/lib/python3.8/site-packages/dnsviz/viz/dnssec.py", line 139, in serialize
    ns_names = list(set([lb2s(map_ip_to_ns_name(s)[0][0].canonicalize().to_text()) for s in servers]))
  File "/home/rithvik/.local/lib/python3.8/site-packages/dnsviz/viz/dnssec.py", line 139, in <listcomp>
    ns_names = list(set([lb2s(map_ip_to_ns_name(s)[0][0].canonicalize().to_text()) for s in servers]))
IndexError: list index out of range
```

---

<details>
<summary>If you're interested in what dig shows - but again, there's an issue with the resolver, which is why it's returning this.</summary>
```
❯ dig @103.196.38.38 nameboard

; <<>> DiG 9.18.0 <<>> @103.196.38.38 nameboard
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31533
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1680
;; QUESTION SECTION:
;nameboard.                     IN      A

;; AUTHORITY SECTION:
nameboard.              3547    IN      SOA     a.misconfigured.powerdns.server. hostmaster.nameboard. 2021112102 10800 3600 604800 3600

;; Query time: 243 msec
;; SERVER: 103.196.38.38#53(103.196.38.38) (UDP)
;; WHEN: Tue Mar 22 22:31:59 IST 2022
;; MSG SIZE  rcvd: 116
```
</details>

**Comment by cdeccio** [comment]
Thanks for this.  I'm a little backlogged 😬 , but I'll try to get to this (and some of the others waiting) in the next month or so.  Thanks!
